### ISSUE TITLE
resolver: Kubernetes lookup by ID doesn't work

### ISSUE THREAD

**Issue by juniorz** [lyft/clutch#257]
**Description**

The Kubernetes resolver's `Search()` fails when querying by a resource ID.

For example, when trying to use the "K8s: Delete Pod" workflow, I can't obtain a pod by ID using the input labeled "Search by pod ID", as it always returns an error. The same also happens for the HPA search.

**Expected Behavior**

I would expect searching for the pod on all namespaces (which might be costly) or just allowing prefixing the pod ID with the namespace (e.g. `default/podname-58448d6d95-znr75`) and passing the namespace along.

**Actual Behavior**

There is always a "Failed Precondition" error, for example: `Failed Precondition: Did not find a 'type.googleapis.com/clutch.k8s.v1.Pod', looked by: pod ID`.

**Version**

Docker image: 
`docker.io/lyft/clutch@sha256:6da4e0c07c93eb744ec213a86951730e4a22496663a2826eace66f17f87b67ef`

**Other Context**

When looking at the source code, I noticed that the k8s backend invokes the service's `DescribePod()` without a namespace:
https://github.com/lyft/clutch/blob/94145f2f7db6dc3abcfe0ec2874de3ee57a3f2e0/backend/resolver/k8s/k8s.go#L158

That will result in a call to `clientset.CoreV1().Pods("").Get(...)` - which is invalid - and will always return the following error due to the empty namespace: `an empty namespace may not be set when a resource name is provided`.

This is also the case when one tries to run `kubectl get pod -A pod-name`

**Comment by mcutalo88** [comment]
Hey @juniorz thanks for the report! I actually noticed this yesterday and just chatted with the team today about the issue. All of the omni searches for the k8s workflows have the same problem, I'm going to to be working on a solution for this soon and rearchitect this a bit.

On the expected behavior,  in the short term we could do the namespace approach this would definitely be a quicker fix. Although if we wanted to support just a pod name, I would use pod informer caches to make look ups much faster. This is work that will be doing soon called topology cache which is on [our roadmap](https://clutch.sh/docs/about/roadmap#platform-improvements).

I'll update the ticket with more info once we have decided on a short / long term direction.

One request, can you update the issue to be generic for all k8s search workflows? The pod example you have here is perfect detail!

**Comment by danielhochman** [comment]
@juniorz #259 fixes the bug where passing the empty namespace from the resolver can never find anything. it is supposed to use the clientset's namespace in that case.

there's still the more open ended question of whether we do more to fan-out to multiple namespaces or allow a namespace to be passed as part of the query in the resolver.
