### ISSUE TITLE
core: display audit trail in UI

### ISSUE THREAD

**Issue by danielhochman** [lyft/clutch#37]
**Description**

Add an audit log viewer to the frontend, on top of the audit API defined in https://github.com/lyft/clutch/blob/master/api/audit/v1/audit.proto.

Complexity [S/M/L]: M

**Wireframes, Mockups, or Screenshots (if applicable)**
TODO

**Comment by autisticvegan** [comment]
Hi, I will be joining Lyft on Feb 8th full-time and was pointed towards this issue since I will be joining this team and had some extra time :).  Here is my doc for my plan:  
https://docs.google.com/document/d/1xmX_gNwxevH4QORS5ujUqzkpQo5lf_O7Smy5MYqC6Uc/edit?usp=sharing

I will schedule office hours for next Tuesday to ask about this.
