### ISSUE TITLE
hadoop tool `yarn` conflicts with javascript `yarn` during build

### ISSUE THREAD

**Issue by henrywu2019** [lyft/clutch#60]
**Description**

The build failed very fast....

Following document: https://clutch.sh/docs/getting-started/local-build

and run `make`

**Expected Behavior**

Build Succeeds.

**Actual Behavior**
```
info: Downloading protoc-v3.11.4 to build environment
info: Downloading protobufjs to build environment
Unrecognized option: --cwd
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Makefile:20: recipe for target 'api' failed
make: *** [api] Error 1
```

**Version**
git master repo

**Comment by danielhochman** [comment]
Thanks for reporting!

The error occurs here [tools/compile-protos.sh:197](https://github.com/lyft/clutch/blob/f86bf5b468d24e473a60f065f48030e7e9ff8002/tools/compile-protos.sh#L197) when installing the javascript tooling for protobuf compilation.

The problem is that `yarn` is also a Hadoop script: https://hadoop.apache.org/docs/r2.4.1/hadoop-yarn/hadoop-yarn-site/YarnCommands.html, whereas we need this `yarn` https://yarnpkg.com/.

We download yarn as its own file anyways in [tools/install-yarn.sh](https://github.com/lyft/clutch/blob/main/tools/install-yarn.sh) so what we can do is have the `Makefile` call this script directly instead of whatever `yarn` is in the users' PATH.

**Comment by danielhochman** [comment]
@henrywu2019 let me know if you still have the issue on the latest master, and reopen the ticket if so.
