### ISSUE TITLE
No workflows found in custom gateway generated by scaffold-gateway 

### ISSUE THREAD

**Issue by wbertelsen** [lyft/clutch#87]
**Description**
When you build a fresh custom gateway using `make scaffold-gateway` all workflows are missing.
**Expected Behavior**
The default workflows, as well as the `echo` workflow, should appear in clutch.
**Actual Behavior**
There are no workflows
![Screenshot from 2020-07-23 18-14-05](https://user-images.githubusercontent.com/1421662/88352913-68d23980-cd10-11ea-954e-b1771af55833.png)

**Version**
124f38193eb44cd29aad4d236fa32ef48ba30257

**Other Context**
I think this is because the workflows in https://github.com/lyft/clutch/blob/124f38193eb44cd29aad4d236fa32ef48ba30257/tools/scaffolding/templates/gateway/frontend/src/clutch.config.js#L2 are missing the proper `@clutch-sh` prefix
https://github.com/lyft/clutch/blob/124f38193eb44cd29aad4d236fa32ef48ba30257/frontend/packages/app/src/clutch.config.js#L2

**Comment by jmcarless** [comment]
Just as a follow-up, I think there is another bug in custom gateway workflow generation. 
Even if I manually fix the above bug, the "echo" workflow fails to register.

I believe this is due to the "yarn list" command in the workflow registrar not finding workflows in the custom gateway workspace.

If I change this line:
https://github.com/lyft/clutch/blob/main/frontend/packages/tools/workflow-registrar.js#L42

to `cwd: '${process.argv[2]}'`, then the yarn list command is able to find the echo workflow.

**Comment by danielhochman** [comment]
Thanks for the report and update! We're actively debugging and figuring out the most robust fixes here. It was difficult to fully test the scaffolding flows before we went live and started publishing packages so we ended up with a few critical bugs. We'll also be adding some more exhaustive tests to the scaffolding output.
