### ISSUE TITLE
resolver: autocomplete for queries

### ISSUE THREAD

**Issue by micnncim** [lyft/clutch#921]
**Description**

I want the autocomplete feature in Resolvers.

It's not been implemented yet though `Resolver` interface has a method for it with comment-out:

https://github.com/lyft/clutch/blob/f14f1e551628e1631bafc08c709c9981db444091/backend/resolver/resolver.go#L41

Also, https://clutch.sh/docs/development/backend/#resolvers says:

> In the future, the resolver will handle autocomplete and asynchronous validation of form input for the frontend.

ref: https://github.com/lyft/clutch/blob/f14f1e551628e1631bafc08c709c9981db444091/docs/about/roadmap.md

Complexity [S/M/L]: M?

**Wireframes, Mockups, or Screenshots (if applicable)**

**Comment by danielhochman** [comment]
@mcutalo88 is working on this as we speak! first he's building it out for the AWS workflows, since they currently do straightforward ID lookups. it is powered by the topology cache that he is also building, since AWS API calls can be slow for users with lots of cloud resources.

later we will also add the ability to transform objects in the topology cache into more complicated formats, such as `{cluster}/{podID}` for k8s.

**Comment by mcutalo88** [comment]
Docs issue created https://github.com/lyft/clutch/issues/1143, going to close this out now!
